rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - rbx-2
#  - jruby
#  - ruby-head
env:
  - JRUBY_OPTS=-Xcext.enabled=true
notifications:
  recipients:
    - ruby-gettext-commit@googlegroups.com
script: bundle exec rake
