rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
#  - rbx-2
#  - jruby
#  - ruby-head
env:
  - JRUBY_OPTS=-Xcext.enabled=true
notifications:
  recipients:
    - ruby-gettext-commit@googlegroups.com
before_install:
  - gem update bundler
script: bundle exec rake
